version: '3.8'

services:
  cf-turnstile:
    image: xinmeng96/cf-turnstile-docker:latest
    container_name: cf-turnstile
    restart: always
    ports:
      - "${TURNSTILE_PUBLIC_PORT:-8080}:80"
    environment:
      - TARGET_SERVER=${TARGET_SERVER:-http://127.0.0.1:1234}
      - PROXY_PORT=${PROXY_PORT:-1234}
    volumes:
      - ./config:/app/config # 持久化配置文件
