version: '3.8'

services:
  turnstile:
    build: .
    container_name: turnstile-container
    environment:
      - TURNSTILE_SECRET_KEY=your_secret_key
      - TARGET_SERVER=http://127.0.0.1
      - TARGET_PORT=1234  # 默认端口为 1234, 可根据需要修改
    ports:
      - "8080:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/index.html:/usr/share/nginx/html/index.html:ro
    restart: always
